name: Zip & Publish

on: 
  workflow_dispatch:
    inputs:
        tag:
          description: 'Define tag'     
          required: true
          default: '1.0.0.0'

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: modDesc.xml modIcon.dds xml/ src/ objects/ material_holders/ hud/ brand/
          recursive: false
          dest: FS22_LiquidLime.zip
      - uses: actions/upload-artifact@v1
        with:
          name: Test
          path: ${{ github.workspace }}/FS22_LiquidLime.zip
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/FS22_LiquidLime.zip
          asset_name: FS22_LiquidLime.zip
          tag: 1.0.1.0
          overwrite: true
          body: "This is my auto release test"
