name: Zip Files

on:
  push:
    branches: [ "main" ]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: modDesc.xml modIcon.dds xml/ src/ objects/ material_holders/ hud/ brand/
          dest: test.zip
