name: Zip & Publish

on: 
  workflow_dispatch:
    inputs:
        tag:
          description: 'Define tag'     
          required: true
          default: '0.0.0.0'

        useartifact:
          description: 'Use Artifact'
          type: boolean
          required: true
          default: false

        uploadrelease:
          description: 'Upload Release'
          type: boolean
          required: true
          default: true

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install zip
      
      - run: zip -r "$ARCHIVE_NAME" modDesc.xml modIcon.dds xml/ src/ objects/ material_holders/ hud/ brand/
        env:
          ARCHIVE_NAME: FS22_LiquidLime.zip
          
     # - uses: papeloto/action-zip@v1
     #   with:
     #     files: modDesc.xml modIcon.dds xml/ src/ objects/ material_holders/ hud/ brand/
     #     recursive: false
     #     dest: FS22_LiquidLime.zip

  release-LL:
    runs-on: ubuntu-latest
    steps:
      - if: inputs.uploadrelease
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ github.workspace }}/FS22_LiquidLime.zip
          tag_name: ${{ inputs.tag }}
          name: ${{ inputs.release_name }}
