name: Zip Files

on:
  push:
    branches: [ "main" ]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: modDesc.xml modIcon.dds xml/ src/ objects/ material_holders/ hud/ brand/
          recursive: false
          dest: FS22_LiquidLime.zip
      - uses: actions/upload-artifact@v1
        with:
          name: Test
          path: ${{ github.workspace }}/FS22_LiquidLime.zip
