name: Zip & Publish

on: 
  workflow_dispatch:
    inputs:
        tag:
          description: 'Define tag'     
          required: true
          default: ''
        useartifact:
          description: 'Use Artifact'
          type: boolean
          required: true
          default: false
        uploadrelease:
          description: 'Upload Release'
          type: boolean
          required: true
          default: false

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: modDesc.xml modIcon.dds xml/ src/ objects/ material_holders/ hud/ brand/
          recursive: false
          dest: FS22_LiquidLime.zip
      - if: github.event.inputs.useartifact == 'true'
        uses: actions/upload-artifact@v1
        with:
          name: Test
          path: ${{ github.workspace }}/FS22_LiquidLime.zip
      - if: github.event.inputs.uploadrelease == 'true'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/FS22_LiquidLime.zip
          asset_name: FS22_LiquidLime.zip
          tag: ${{ github.event.inputs.tag }}
          overwrite: true
          body: "This is my auto release test"
